name: 2.0.0.$(Build.BuildId)
# Set variables once
variables:
  - group: dotnet
  - group: nuget
  - name: configuration
    value: Release
  - name: project
    value: "SinKien.IBAN4Net.NetStandard\\SinKien.IBAN4Net.NetStandard.csproj"
trigger:
  branches:
    include:
      - master
pool:
    name: Default
  
steps:
  - task: UseDotNet@2
    displayName: 'use dotnet sdk@$(dotnet.version)'
    inputs:
      packageType: 'sdk'
      version: '$(dotnet.version)'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: $(project)
      feedsToUse: config
      nugetConfigPath: '$(nuget.config)'
      verbosityRestore: Minimal
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: $(project)
      arguments: '-c $(configuration) --no-restore'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: $(project)
      nobuild: true
      includesymbols: true
      versioningScheme: byBuildNumber
      buildProperties: 'Configuration=$(configuration)'
      verbosityPack: Minimal
  
  - script: |
     dotnet nuget push -k $(nuget.apiKey) -s $(nuget.source) $(Build.ArtifactStagingDirectory)\SinKien.IBAN4Net.2.0.0.$(Build.BuildId).nupkg
     dotnet nuget push -k $(nuget.apiKey) -s $(nuget.source) $(Build.ArtifactStagingDirectory)\SinKien.IBAN4Net.2.0.0.$(Build.BuildId).symbols.nupkg
    displayName: 'dotnet push'
  